//! One FRI fold step: pair evaluations at `x` and `-x` on a multiplicative subgroup.

use probatum_field::Field;
use thiserror::Error;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum FoldError {
    #[error("fold input length {0} must be a power of two and at least 2")]
    InvalidLength(usize),
}

/// `vals[i]` = `f(ω^i)` for primitive `n`-th root `ω`, `n = vals.len()`.
///
/// Returns `n/2` evaluations of the folded polynomial on the subgroup generated by `ω^2`, at points `(ω^2)^j` for `j = 0..n/2-1`:
///
/// `g((ω^2)^j) = (f(ω^j) + f(-ω^j))/2 + β · (f(ω^j) - f(-ω^j)) / (2·ω^j)` with `-ω^j = ω^{j+n/2}`.
pub fn fold_layer(vals: &[Field], omega: Field, beta: Field) -> Result<Vec<Field>, FoldError> {
    let n = vals.len();
    if n < 2 || !n.is_power_of_two() {
        return Err(FoldError::InvalidLength(n));
    }
    let half = n / 2;
    let mut out = Vec::with_capacity(half);
    for j in 0..half {
        let x = omega.pow(j as u64);
        let f_x = vals[j];
        let f_neg_x = vals[half + j];
        out.push(fold_pair_at_x(f_x, f_neg_x, x, beta));
    }
    Ok(out)
}

/// Single fold pair at point `x` (evaluation domain uses `x = ω^j`).
#[must_use]
pub fn fold_pair_at_x(f_x: Field, f_neg_x: Field, x: Field, beta: Field) -> Field {
    let inv2 = Field::from_u64(2).inv().expect("2 invertible");
    let sum = f_x + f_neg_x;
    let diff = f_x - f_neg_x;
    let two_x = Field::from_u64(2) * x;
    let denom_inv = two_x.inv().expect("2x nonzero for FRI domain points");
    sum * inv2 + beta * diff * denom_inv
}

/// Primitive `n`-th root for current layer (`n` power of two).
#[must_use]
pub fn domain_generator(n: usize) -> Option<Field> {
    if n < 2 || !n.is_power_of_two() {
        return None;
    }
    let k = n.trailing_zeros();
    Field::primitive_root_of_unity(k)
}

/// Generator for the next (halved) domain: `ω^2` if `ω` generates the `n`-element subgroup.
#[must_use]
pub fn next_domain_generator(omega: Field) -> Field {
    omega * omega
}

#[cfg(test)]
mod tests {
    use super::*;
    use probatum_field::MODULUS;

    #[test]
    fn constant_poly_stays_constant() {
        let n = 8usize;
        let omega = domain_generator(n).expect("omega");
        let c = Field::new(42);
        let vals = vec![c; n];
        let beta = Field::new(7);
        let folded = fold_layer(&vals, omega, beta).expect("fold");
        assert_eq!(folded.len(), 4);
        assert!(folded.iter().all(|x| *x == c));
    }

    #[test]
    fn fold_then_size_halves() {
        let n = 32usize;
        let omega = domain_generator(n).expect("omega");
        let vals: Vec<Field> = (0..n).map(|i| Field::new((i as u64 * 11 + 3) % MODULUS)).collect();
        let beta = Field::new(123);
        let f1 = fold_layer(&vals, omega, beta).expect("fold");
        assert_eq!(f1.len(), 16);
        let omega1 = next_domain_generator(omega);
        let f2 = fold_layer(&f1, omega1, beta).expect("fold");
        assert_eq!(f2.len(), 8);
    }
}
